/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetDisplayNameRouteImport } from './routes/set-display-name'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PicksStepRouteImport } from './routes/picks.$step'

const SetDisplayNameRoute = SetDisplayNameRouteImport.update({
  id: '/set-display-name',
  path: '/set-display-name',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksStepRoute = PicksStepRouteImport.update({
  id: '/picks/$step',
  path: '/picks/$step',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/set-display-name': typeof SetDisplayNameRoute
  '/picks/$step': typeof PicksStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/set-display-name': typeof SetDisplayNameRoute
  '/picks/$step': typeof PicksStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/set-display-name': typeof SetDisplayNameRoute
  '/picks/$step': typeof PicksStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/set-display-name' | '/picks/$step'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/set-display-name' | '/picks/$step'
  id: '__root__' | '/' | '/set-display-name' | '/picks/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetDisplayNameRoute: typeof SetDisplayNameRoute
  PicksStepRoute: typeof PicksStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-display-name': {
      id: '/set-display-name'
      path: '/set-display-name'
      fullPath: '/set-display-name'
      preLoaderRoute: typeof SetDisplayNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks/$step': {
      id: '/picks/$step'
      path: '/picks/$step'
      fullPath: '/picks/$step'
      preLoaderRoute: typeof PicksStepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetDisplayNameRoute: SetDisplayNameRoute,
  PicksStepRoute: PicksStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
